---
fullname: Buchberger
shortname: buchberger
organization: palmskog
community: false
travis: true
coqdoc: false

synopsis: Coq proof of the correctness of Buchberger's algorithm

description: |-
  A machine-checked implementation of Buchberger's algorithm,
  which computes the Gröbner basis associated with a polynomial ideal.

publications:
- pub_url: https://link.springer.com/article/10.1023/A:1026518331905
  pub_title: A machine checked implementation of Buchberger's algorithm
  pub_doi: 10.1023/A:1026518331905

authors:
- name: Laurent Théry
  initial: true
- name: Henrik Persson
  initial: true

opam-file-maintainer: palmskog@gmail.com

opam-file-version: dev

license:
  fullname: GNU Lesser General Public License v2.1
  identifier: LGPL-2.1-only

supported_coq_versions:
  text: 8.7 or later
  opam: '{(>= "8.7" & < "8.12~") | (= "dev")}'

tested_coq_nix_versions:
- version_or_url: https://github.com/coq/coq-on-cachix/tarball/master
- version_or_url: '8.11'
- version_or_url: '8.10'
- version_or_url: '8.9'
- version_or_url: '8.8'
- version_or_url: '8.7'

tested_coq_opam_versions:
- version: dev

namespace: Buchberger

keywords:
- name: Gröbner basis
- name: polynomial ideal
- name: Buchberger's algorithm

categories:
- name: Mathematics/Algebra
- name: Miscellaneous/Extracted Programs/Combinatorics

documentation: |-
  ## Documentation

  This project contains a Coq formalization of Buchberger's algorithm.

  It is composed of:
  - A proof of correctness of the algorithm as described in
  A machine checked implementation of Buchberger's algorithm, JAR, January 2001.
  - An implementation of the algorithm. With respect to the paper,
  terms are not abstracted but built directly from coef and monomials.
  - A constructive proof of Dickson's lemma due to Henrik Persson.
  
  In `Extract.v`, it is explained how the extracted code found in
  `sin_num.ml` can be used to compute Gröbner bases.
---
